# Generated by Django 6.0.5 on 2026-05-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenseentry',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transport'), ('college', 'College Fees & Education'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities & Bills'), ('shopping', 'Shopping'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
