# Generated by Django 6.0.5 on 2026-05-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expenseentry_options_alter_expenseentry_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transport'), ('college', 'College Fees & Education'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities & Bills'), ('shopping', 'Shopping'), ('health', 'Health & Medical'), ('other', 'Other')], max_length=20),
        ),
    ]
