# Generated by Django 6.0.5 on 2026-05-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenseentry_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseentry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='savings_goal',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('college', 'College'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('health', 'Health'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
    ]
